<?php

namespace AppBundle\Repository;

/**
 * BuildingInProccessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildingInProccessRepository extends \Doctrine\ORM\EntityRepository
{
}
