<?php

namespace AppBundle\Repository;

/**
 * FlightsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlightsRepository extends \Doctrine\ORM\EntityRepository
{
}
