<?php

namespace AppBundle\Repository;

/**
 * GameActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameActivityRepository extends \Doctrine\ORM\EntityRepository
{
}
