<?php

namespace AppBundle\Repository;

/**
 * PlanetShipsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanetShipsRepository extends \Doctrine\ORM\EntityRepository
{
}
