<?php

namespace AppBundle\Repository;

/**
 * PlanetBuildingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanetBuildingRepository extends \Doctrine\ORM\EntityRepository
{
}
