<?php

namespace AppBundle\Repository;

/**
 * ShipsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipsRepository extends \Doctrine\ORM\EntityRepository
{
}
