<?php

namespace AppBundle\Repository;

/**
 * ShipsCostResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipsCostResourceRepository extends \Doctrine\ORM\EntityRepository
{
}
