<?php

namespace AppBundle\Repository;

/**
 * ShipsInProccessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipsInProccessRepository extends \Doctrine\ORM\EntityRepository
{
}
