<?php

namespace AppBundle\Repository;

/**
 * ShipsCostTimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipsCostTimeRepository extends \Doctrine\ORM\EntityRepository
{
}
